language: node_js
node_js:
  - 9
os:
  - linux
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 8676121626c805efaf4552c20c09c8611fa9c6ac  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
