language: node_js
node_js:
  - 9
os:
  - linux
dist: trusty
sudo: required

before_script:
  - npm install -g @angular/cli

branches:
  only:
  - master
  
script:
- ng lint
- ng build --prod --base-href https://tester1313.github.io/teste-deploy/

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/travis-demo
  on:
    branch: master
