language: node_js
node_js:
  - 9
os:
  - linux
dist: trusty
sudo: required

before_script:
  - npm install -g @angular/cli

branches:
  only:
  - master
  
script:
- ng lint
- ng build --prod --base-href https://tester1313.github.io/teste-deploy/
